import type { KamisPriceResponse } from "@/lib/kamis/types";

export const mockDailyPricePages: KamisPriceResponse[] = [
  {
    sourceCode: "KAMIS",
    nextCursor: "page-2",
    records: [
      {
        date: "2026-06-05",
        itemCode: "KAMIS-BAECHU",
        itemName: "배추",
        kindCode: "GREEN",
        kindName: "봄배추",
        category: "vegetable",
        unit: "1포기",
        unitType: "unknown",
        rank: "middle",
        wsrt: "retail",
        regionCode: null,
        price: "3,200",
        prevDay: "3,100",
        m1Ma5: "3,050",
        y1Ma5: "2,900",
        normal3yr: "2,850",
      },
      {
        date: "2026-06-05",
        itemCode: "KAMIS-MU",
        itemName: "무",
        kindCode: "WHITE",
        kindName: "월동무",
        category: "vegetable",
        unit: "1개",
        unitType: "unknown",
        rank: "middle",
        wsrt: "retail",
        regionCode: null,
        price: "-",
        prevDay: "-",
        m1Ma5: "1,450",
        y1Ma5: "1,300",
        normal3yr: "1,250",
      },
    ],
  },
  {
    sourceCode: "KAMIS",
    nextCursor: null,
    records: [
      {
        date: "2026-06-05",
        itemCode: "KAMIS-APPLE",
        itemName: "사과",
        kindCode: "FUJI",
        kindName: "후지",
        category: "fruit",
        unit: "10개",
        unitType: "unknown",
        rank: "middle",
        wsrt: "wholesale",
        regionCode: null,
        price: "28,000",
        prevDay: "27,500",
        m1Ma5: "26,900",
        y1Ma5: "24,000",
        normal3yr: "23,300",
      },
    ],
  },
];

